//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymulatorNSP.GUI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymulatorNSP.GUI.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Any].
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose random.
        /// </summary>
        public static string ChooseRandom {
            get {
                return ResourceManager.GetString("ChooseRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classified as.
        /// </summary>
        public static string ClassifiedAs {
            get {
                return ResourceManager.GetString("ClassifiedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} out of {1}..
        /// </summary>
        public static string CreationProgressUpdate {
            get {
                return ResourceManager.GetString("CreationProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomasz Skowron.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set desired population count.
        /// </summary>
        public static string DesiredPopulationCount {
            get {
                return ResourceManager.GetString("DesiredPopulationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected population be between 0 and 100000000.
        /// </summary>
        public static string DesiredPopulationCountRangeError {
            get {
                return ResourceManager.GetString("DesiredPopulationCountRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select difference calculation method.
        /// </summary>
        public static string DistanceCalculationMethod {
            get {
                return ResourceManager.GetString("DistanceCalculationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some people might have an error in their entries. For example misspelling in nationality like &quot;german&quot; they might have an entry &quot;g3rman&quot;. Here you can select an algorithm that will tolerate errors (up to a few characters changed). Select &quot;-&quot; if you want to see only exact matches in the query matching process and disable any tolerance to errors. By searching &quot;unrecognized&quot; in filter field for a specific query you can check how many entries had too big differences from options defined in generator configurati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DistanceExaplanation {
            get {
                return ResourceManager.GetString("DistanceExaplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing distance.
        /// </summary>
        public static string EditingDistance {
            get {
                return ResourceManager.GetString("EditingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file name.
        /// </summary>
        public static string EnterFileName {
            get {
                return ResourceManager.GetString("EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity - error rate:.
        /// </summary>
        public static string EthnicityErrorRate {
            get {
                return ResourceManager.GetString("EthnicityErrorRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity - maximum number of affected letters:.
        /// </summary>
        public static string EthnicityMaxErrorImpact {
            get {
                return ResourceManager.GetString("EthnicityMaxErrorImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute query.
        /// </summary>
        public static string ExecuteQuery {
            get {
                return ResourceManager.GetString("ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time.
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishStep.
        /// </summary>
        public static string FinishStep {
            get {
                return ResourceManager.GetString("FinishStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Original {0} could not be classified. Smallest editing distance was equal to: {2} for option {1} and the algorithm used {3}.
        /// </summary>
        public static string FitFailure {
            get {
                return ResourceManager.GetString("FitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS Original {0} was classified as {1}. Editing distance was equal to: {2} and the algorithm used {3}.
        /// </summary>
        public static string FitSuccess {
            get {
                return ResourceManager.GetString("FitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regios Association (KRS: 0000976963) www.regios.org.pl.
        /// </summary>
        public static string GDPRAdmin {
            get {
                return ResourceManager.GetString("GDPRAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Administrator.
        /// </summary>
        public static string GDPRAdminTitle {
            get {
                return ResourceManager.GetString("GDPRAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string GDPRPrivacyPolicyLabel {
            get {
                return ResourceManager.GetString("GDPRPrivacyPolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPR.
        /// </summary>
        public static string GDRPLabel {
            get {
                return ResourceManager.GetString("GDRPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate population.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please generate population first!.
        /// </summary>
        public static string GeneratePopulationFirst {
            get {
                return ResourceManager.GetString("GeneratePopulationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation Configuration.
        /// </summary>
        public static string GenerationConfiguration {
            get {
                return ResourceManager.GetString("GenerationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on the records that are randomly generated you will get various query execution times. Each record has a few properties (eg. Name, Surname, Nationality...) and each property value (eg. Smith or De-La-Rosa-Ramirez) length will also impact the execution times. You can change the list of property values that will be available to the generator and probability with which they will be chosen. Configurations also contain some properties that simulate (real-life scenario) misspelings in Nationality proper [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenerationConfigurationDescription {
            get {
                return ResourceManager.GetString("GenerationConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load population.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not loaded.
        /// </summary>
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loaded successfully.
        /// </summary>
        public static string LoadSuccess {
            get {
                return ResourceManager.GetString("LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log population sample.
        /// </summary>
        public static string LogPopulationSample {
            get {
                return ResourceManager.GetString("LogPopulationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality - error rate.
        /// </summary>
        public static string NationalityErrorRate {
            get {
                return ResourceManager.GetString("NationalityErrorRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality - maximum number of affected letters.
        /// </summary>
        public static string NationalityMaxErrorImpact {
            get {
                return ResourceManager.GetString("NationalityMaxErrorImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records.
        /// </summary>
        public static string NumberOfRecords {
            get {
                return ResourceManager.GetString("NumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance factor.
        /// </summary>
        public static string PerformanceFactor {
            get {
                return ResourceManager.GetString("PerformanceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your execution time and records count we calculate a fair performance factor relative to GUS computation time. It is relative to number of records that GUS had to calculate, so if your query was done in 5 sec for 1 mln records, your factor will be divided by ~(1/38)..
        /// </summary>
        public static string PerformanceFactorExplanation {
            get {
                return ResourceManager.GetString("PerformanceFactorExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} 
        ///Surname: {1} 
        ///Address: {2}
        ///Religion: {3} 
        ///Nationality: {4} 
        ///Job: {5}.
        /// </summary>
        public static string PersonStringified {
            get {
                return ResourceManager.GetString("PersonStringified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records queried.
        /// </summary>
        public static string QueriedRecordsCount {
            get {
                return ResourceManager.GetString("QueriedRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query end.
        /// </summary>
        public static string QueryEnd {
            get {
                return ResourceManager.GetString("QueryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query by ethnicity.
        /// </summary>
        public static string QueryEthnicity {
            get {
                return ResourceManager.GetString("QueryEthnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query execution time.
        /// </summary>
        public static string QueryExecutionTime {
            get {
                return ResourceManager.GetString("QueryExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t print more than 1000 samples!.
        /// </summary>
        public static string QueryLimitThousandSamples {
            get {
                return ResourceManager.GetString("QueryLimitThousandSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query by nationality.
        /// </summary>
        public static string QueryNationality {
            get {
                return ResourceManager.GetString("QueryNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query in both nationality and ethnicity.
        /// </summary>
        public static string QueryNationalityOrEthnicity {
            get {
                return ResourceManager.GetString("QueryNationalityOrEthnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of matches | Total.
        /// </summary>
        public static string QueryResultsCount {
            get {
                return ResourceManager.GetString("QueryResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query start.
        /// </summary>
        public static string QueryStart {
            get {
                return ResourceManager.GetString("QueryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query filter.
        /// </summary>
        public static string QueryValue {
            get {
                return ResourceManager.GetString("QueryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You queried {0} records and counted them all in {1} seconds. Central Statistical Office needed more than {2} seconds to query ~38 mln records. Congratulations you are {3} times faster!.
        /// </summary>
        public static string RealLifeComparisonStringCotent {
            get {
                return ResourceManager.GetString("RealLifeComparisonStringCotent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string RealLifeComparisonStringTitle {
            get {
                return ResourceManager.GetString("RealLifeComparisonStringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string RecordKey {
            get {
                return ResourceManager.GetString("RecordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is your first submission this key will be used to protect your record from being overwritten. Otherwise please enter the same Nickname and Key pair to overrwrite your previous result in the leaderboard..
        /// </summary>
        public static string RecordKeyExplanation {
            get {
                return ResourceManager.GetString("RecordKeyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save population.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not saved.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send result to leaderboard.
        /// </summary>
        public static string SendResultsToLeaderboard {
            get {
                return ResourceManager.GetString("SendResultsToLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Generate population.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 10. Share your results.
        /// </summary>
        public static string Step10 {
            get {
                return ResourceManager.GetString("Step10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2. View sample population record.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3. Perform queries.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4. (Optional) Change configuration.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish step 4.
        /// </summary>
        public static string Step4Finish {
            get {
                return ResourceManager.GetString("Step4Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please feel free to make changes to the configuration. You can add options for generating objects, change error chance and error impact for nationality property to simulate real life scenario. Later you can use difference calculating algorithms to automate process of bucketing entries with errors into available options..
        /// </summary>
        public static string Step4nExplanation {
            get {
                return ResourceManager.GetString("Step4nExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.1 (Optional) Change error rate.
        /// </summary>
        public static string Step4p1 {
            get {
                return ResourceManager.GetString("Step4p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the error rate of nationality in the records. That way you can simulate real-life scenario. By changing error rate you change the chance that a generated record will contain a misspelling. By changing the impact parameter you specify what is the maximum number of misspelled characters. Keep in mind that bucketing function that calculates editing distance in further steps has a hardcoded limit of 2 misspelled characters. Any record with more than 2 characters that do not match any option will  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Step4p1Explanation {
            get {
                return ResourceManager.GetString("Step4p1Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.2 (Optional) Change configuration details.
        /// </summary>
        public static string Step4p2 {
            get {
                return ResourceManager.GetString("Step4p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can edit all the details of the configuration. It is presented as JSON object. Make sure that you unfocus from editor only when the configuration contains no formatting errors. Any changes will be lost if you change to any other preset configuration or if the configuration was incorrect. To avoid format errors try using any external tool like: https://jsonformatter.curiousconcept.com/.
        /// </summary>
        public static string Step4p2Explanation {
            get {
                return ResourceManager.GetString("Step4p2Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.3 (Optional) Change number of CPU threads.
        /// </summary>
        public static string Step4p3 {
            get {
                return ResourceManager.GetString("Step4p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5. (Optional) Regenerate population with custom configuration.
        /// </summary>
        public static string Step5 {
            get {
                return ResourceManager.GetString("Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6. (Optional) Enable transparency mode.
        /// </summary>
        public static string Step6 {
            get {
                return ResourceManager.GetString("Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 7. (Optional ) Select editing distance calculation method.
        /// </summary>
        public static string Step7 {
            get {
                return ResourceManager.GetString("Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 8. (Optional) View sample population record.
        /// </summary>
        public static string Step8 {
            get {
                return ResourceManager.GetString("Step8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 9. (Optional) Query with custom configuration.
        /// </summary>
        public static string Step9 {
            get {
                return ResourceManager.GetString("Step9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string Threads {
            get {
                return ResourceManager.GetString("Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of records.
        /// </summary>
        public static string TotalNumberOfRecords {
            get {
                return ResourceManager.GetString("TotalNumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode will show results if you meet all these conditions: NationalityErrorRate is bigger than zero, your records do contain misspellings (they might not have misspellings if your error rate and generated population size were small), NationalityMaxImpact is bigger than 0, TransparencyMode is enabled and you are using either Levenstein or Hamming algorithm (if none of them is in use, then there are no results to be shown, because only exact ones are classified)..
        /// </summary>
        public static string TransparenceModePrerequisites {
            get {
                return ResourceManager.GetString("TransparenceModePrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode is nof OFF!.
        /// </summary>
        public static string TransparenctModeOFF {
            get {
                return ResourceManager.GetString("TransparenctModeOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode.
        /// </summary>
        public static string TransparencyMode {
            get {
                return ResourceManager.GetString("TransparencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent mode will show you information about automatic fitting of error-like entries (the ones misspelings if you configured ErrorRate and ErrorMaxImpact in previous steps). Keep in mind that, it might negatively impact the application performance and query execution time..
        /// </summary>
        public static string TransparencyModeExplanation {
            get {
                return ResourceManager.GetString("TransparencyModeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode is now ON!.
        /// </summary>
        public static string TransparencyModeON {
            get {
                return ResourceManager.GetString("TransparencyModeON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode results.
        /// </summary>
        public static string TransparencyModeResults {
            get {
                return ResourceManager.GetString("TransparencyModeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These results show how an algorithm can deal with custom user input and automatically classify misspelled string to existing bucket. Sometimes you will experience better fits and sometimes they will not be absolutely correct, but Levenstein and Hamming algorithms are the simplest of simplest. There are lots of algorithms that not only can classify data, but also themselves create groups for new data. So for example if GUS has not forseen that &quot;european&quot; or &quot;opolean&quot; or &quot;wilamovian&quot; nationality can be an opt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TransparencyModeResultsExplanation {
            get {
                return ResourceManager.GetString("TransparencyModeResultsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For optimization purposes this list may contain up to 100 fitting results, even though the querying process might have generated more..
        /// </summary>
        public static string TransparencyModeResultsLimitation {
            get {
                return ResourceManager.GetString("TransparencyModeResultsLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will impact execution time!.
        /// </summary>
        public static string TransparencyModeWaringingTooltip {
            get {
                return ResourceManager.GetString("TransparencyModeWaringingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Unrecognized Statistical Office!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Application.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
