//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymulatorNSP.Startup.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymulatorNSP.Startup.Strings.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Any].
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSP Simulator 2021 - WINDOWS.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced mode.
        /// </summary>
        internal static string ComplexMode {
            get {
                return ResourceManager.GetString("ComplexMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set desired population count.
        /// </summary>
        internal static string DesiredPopulationCount {
            get {
                return ResourceManager.GetString("DesiredPopulationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select difference calculation method.
        /// </summary>
        internal static string DistanceCalculationMethod {
            get {
                return ResourceManager.GetString("DistanceCalculationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute query.
        /// </summary>
        internal static string ExecuteQuery {
            get {
                return ResourceManager.GetString("ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate population.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation Configuration.
        /// </summary>
        internal static string GenerationConfiguration {
            get {
                return ResourceManager.GetString("GenerationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open leaderboard.
        /// </summary>
        internal static string OpenLeaderboard {
            get {
                return ResourceManager.GetString("OpenLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        internal static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query end.
        /// </summary>
        internal static string QueryEnd {
            get {
                return ResourceManager.GetString("QueryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query by ethnicity.
        /// </summary>
        internal static string QueryEthnicity {
            get {
                return ResourceManager.GetString("QueryEthnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query execution time.
        /// </summary>
        internal static string QueryExecutionTime {
            get {
                return ResourceManager.GetString("QueryExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query by nationality.
        /// </summary>
        internal static string QueryNationality {
            get {
                return ResourceManager.GetString("QueryNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query in both nationality and ethnicity.
        /// </summary>
        internal static string QueryNationalityOrEthnicity {
            get {
                return ResourceManager.GetString("QueryNationalityOrEthnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of matches | Total:.
        /// </summary>
        internal static string QueryResultsCount {
            get {
                return ResourceManager.GetString("QueryResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query start.
        /// </summary>
        internal static string QueryStart {
            get {
                return ResourceManager.GetString("QueryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query filter.
        /// </summary>
        internal static string QueryValue {
            get {
                return ResourceManager.GetString("QueryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple mode.
        /// </summary>
        internal static string SimpleMode {
            get {
                return ResourceManager.GetString("SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency mode.
        /// </summary>
        internal static string TransparencyMode {
            get {
                return ResourceManager.GetString("TransparencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Unrecognized Statistical Office!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
