//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymulatorNSP.Shared.WebsiteLocResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebsiteLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymulatorNSP.Shared.WebsiteLocResources.WebsiteLoc", typeof(WebsiteLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projec was initiated by REGIOS Association to show the innefficiency of Central Statistical Office (GUS) in Poland. Unlike GUS we believe in full transparency and we share the source code of the application on a Github Repository..
        /// </summary>
        internal static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application developer: tomasz.skowron@regios.org.pl.
        /// </summary>
        internal static string ApplicationContact {
            get {
                return ResourceManager.GetString("ApplicationContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2021 in Poland Central Statistical Office (GUS) performed a National Census (NSP). However they did not publish any results about ethnic and national structure for more than a year after the census was closed. It is worth noting that some information was published by GUS in Q4 2022 and it was used to create a default configuration for SymulatorNSP application. 
        ///
        ///On this website you can check how much faster your browser is than whole GUS office, that could not manage to calculate those results for more [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BackgroundDescription {
            get {
                return ResourceManager.GetString("BackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundHeader {
            get {
                return ResourceManager.GetString("BackgroundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately browser version supports up to 1.000.000 generated records. Later you may choose to query more records, but in browser version it will be done using the same dataset, just multiple times. For full experience without this limitation please check out the PC version of NSP Simulator 2022..
        /// </summary>
        internal static string BrowserLimitExplanation {
            get {
                return ResourceManager.GetString("BrowserLimitExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser limit reached!.
        /// </summary>
        internal static string BrowserLimitHeader {
            get {
                return ResourceManager.GetString("BrowserLimitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately at the moment the application supports only 1 thread for the browser. If you want to test your performance with multiple threads chech out the PC version..
        /// </summary>
        internal static string BrowserLimitOneThread {
            get {
                return ResourceManager.GetString("BrowserLimitOneThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that this is just a browser!.
        /// </summary>
        internal static string CheckOutMoreHeader {
            get {
                return ResourceManager.GetString("CheckOutMoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While testing the Windows version of NSP Simulator 2021, we managed to query 38 mln results in less than 5 seconds! Also feel free to explore our advanced NSP Simulator Online, where you can configure the way that records are generated, add errors into the records, and explore performance of the searching algorithm when discance calculating methods (Levenstein and Hamming) are used to bucket misspelled strings into available options..
        /// </summary>
        internal static string CheckOutMoreValue {
            get {
                return ResourceManager.GetString("CheckOutMoreValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPR: rodo@regios.org.pl.
        /// </summary>
        internal static string GDPRContact {
            get {
                return ResourceManager.GetString("GDPRContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/skowront/SymulatorNSP2021.
        /// </summary>
        internal static string GithubREPOLink {
            get {
                return ResourceManager.GetString("GithubREPOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows NSP Simulator.
        /// </summary>
        internal static string GUSForPCLabel {
            get {
                return ResourceManager.GetString("GUSForPCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online NSP Simulator (full version).
        /// </summary>
        internal static string GUSOnlineLabel {
            get {
                return ResourceManager.GetString("GUSOnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        internal static string LeaderboardLabel {
            get {
                return ResourceManager.GetString("LeaderboardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media: biuro@regios.org.pl.
        /// </summary>
        internal static string MediaContact {
            get {
                return ResourceManager.GetString("MediaContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextLabel {
            get {
                return ResourceManager.GetString("NextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other: biuro@regios.org.pl.
        /// </summary>
        internal static string OtherContact {
            get {
                return ResourceManager.GetString("OtherContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousLabel {
            get {
                return ResourceManager.GetString("PreviousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start small, go big! Remember that browser applications are a lot slower than standard executables. We highly recommend to go with 1 mln records for starters. Remember to check out Symulator NSP for Windows later and see the true power of moder computation. In both cases you will, most likely, leave GUS behind..
        /// </summary>
        internal static string QueryAmountRemark {
            get {
                return ResourceManager.GetString("QueryAmountRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For browsers we recommend to generate at least 10000 records..
        /// </summary>
        internal static string RecommendedPopulationSize {
            get {
                return ResourceManager.GetString("RecommendedPopulationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesDescription.
        /// </summary>
        internal static string ResourcesDescription {
            get {
                return ResourceManager.GetString("ResourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesHeader.
        /// </summary>
        internal static string ResourcesHeader {
            get {
                return ResourceManager.GetString("ResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number of rows to be queried.
        /// </summary>
        internal static string SelectQueryAmountDescription {
            get {
                return ResourceManager.GetString("SelectQueryAmountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server unavailable.
        /// </summary>
        internal static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step1Description.
        /// </summary>
        internal static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2Description.
        /// </summary>
        internal static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step2Header.
        /// </summary>
        internal static string Step2Header {
            get {
                return ResourceManager.GetString("Step2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3Description.
        /// </summary>
        internal static string Step3Description {
            get {
                return ResourceManager.GetString("Step3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step3Header.
        /// </summary>
        internal static string Step3Header {
            get {
                return ResourceManager.GetString("Step3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps1Header.
        /// </summary>
        internal static string Steps1Header {
            get {
                return ResourceManager.GetString("Steps1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your results to leaderboard.
        /// </summary>
        internal static string SubmitYourResults {
            get {
                return ResourceManager.GetString("SubmitYourResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can take a while..
        /// </summary>
        internal static string ThisCanTakeAWhile {
            get {
                return ResourceManager.GetString("ThisCanTakeAWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying 38 mln records with a browser can take several minutes. The same can be done in seconds if you will use our NSP Simulator for Windows PC. Remember to check it out later..
        /// </summary>
        internal static string ThisCanTakeAWhileExplanation {
            get {
                return ResourceManager.GetString("ThisCanTakeAWhileExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again later....
        /// </summary>
        internal static string TryAgainLater {
            get {
                return ResourceManager.GetString("TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, sorry! Please reload the page....
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSP Simulator 2021.
        /// </summary>
        internal static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to NSP Simulator 2021 site!.
        /// </summary>
        internal static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can check how much faster is your PC than Central Statistical Office (GUS) in Poland..
        /// </summary>
        internal static string WelcomeSubHeader {
            get {
                return ResourceManager.GetString("WelcomeSubHeader", resourceCulture);
            }
        }
    }
}
