//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymulatorNSP.Shared.WindowsTutorialResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindowsTutorial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowsTutorial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymulatorNSP.Shared.WindowsTutorialResources.WindowsTutorial", typeof(WindowsTutorial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest version of Simulator NSP for Windows from.
        /// </summary>
        public static string Step1Description {
            get {
                return ResourceManager.GetString("Step1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/skowront/SymulatorNSP2021/releases/tag/major.
        /// </summary>
        public static string Step1DownloadLink {
            get {
                return ResourceManager.GetString("Step1DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip the file.
        /// </summary>
        public static string Step2Description {
            get {
                return ResourceManager.GetString("Step2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymulatorNSP-Release.1.x.0.0.zip.
        /// </summary>
        public static string Step2FileName {
            get {
                return ResourceManager.GetString("Step2FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Step3Description {
            get {
                return ResourceManager.GetString("Step3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymulatorNSP.Startup.exe.
        /// </summary>
        public static string Step3FileName {
            get {
                return ResourceManager.GetString("Step3FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select simple or advanced mode. Simple mode is similar to what you saw on the home page in the browser, while advanced mode is more like the extended browser version of NSP Simulator 2021 which you can select from the navigation menu..
        /// </summary>
        public static string Step4Description {
            get {
                return ResourceManager.GetString("Step4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Step5 {
            get {
                return ResourceManager.GetString("Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out how fast your PC is. Remember to try increasing threads count in the advanced mode and play around with the configuration..
        /// </summary>
        public static string Step5Description {
            get {
                return ResourceManager.GetString("Step5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your results.
        /// </summary>
        public static string Step6 {
            get {
                return ResourceManager.GetString("Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform some queries and share your results to the online leaderboard..
        /// </summary>
        public static string Step6Description {
            get {
                return ResourceManager.GetString("Step6Description", resourceCulture);
            }
        }
    }
}
